### ISSUE TITLE
User avatar not displayed besides the post

### ISSUE THREAD

**Issue by dguenms** [ClangPan/dashboard-unfucker#1]
**Describe the bug**
Hey, first of all thank you so much for putting in the work and restoring this script back to working state. It's mostly working for me and I already feel so much more at home again on my dash.

I do have a minor issue: to me the settings imply that the script is able to restore the old "user avatar/icon displayed left of the post" look that tumblr used to have. At least that is my reading of the "Revert the post header design and re-add user avatars beside posts" setting. However, even with this option enabled the user avatar is still displayed on the top left within the post box to the left of the user name.

**To Reproduce**
1. Check the "Revert the post header design and re-add user avatars beside posts" option so the toggle is to the right
2. Reload the page

The only thing that does show up is my own user avatar at the top of the dash left of the buttons to create a new post. I have the "endless scrolling" option disabled in the tumblr settings, if that is relevant.

**Screenshots**
![Screenshot 2024-06-29 144523](https://github.com/ClangPan/dashboard-unfucker/assets/5592111/43857c57-6453-4e82-924e-f4007a11fc69)
(example of the issue - I would expect the avatar left of "lastvalyrian" to be outside of the post box on the left)

**Version (please complete the following information):**
 - Browser and version: Firefox 127.0.2
 - Script version: 6.1.0
 - OS: Windows 11

**Enabled features**
Exported preferences JSON:
[dashboard unfucker config export 2024-7-29.json](https://github.com/user-attachments/files/16040205/dashboard.unfucker.config.export.2024-7-29.json)

**Additional context**
Please let me know if I can help debug this on my particular configuration. Thanks for the support!

**Comment by frousties** [comment]
Hmm your config indeed looks healthy, but I also notice in your screenshot that the Tumblr logo is hidden on your side

Do you have any other extension on? Particularly something like uBlock? Does this issue still happens when your disable your other extensions?

Also, if you can, can you do F12 -> Console, and tell me if you see any error that pop up there?

**Comment by dguenms** [comment]
You're right, sorry about that! I do indeed have ublock origin active, with a bunch of custom element blockers I have accumulated over time to fight some of tumblr's nonsense. I removed all of them and the problem persists. The same is true when disabling ublock origin entirely. Even disabling all other extensions (I have a set of anti tracking and anti ad extensions running) besides tampermonkey makes no difference. This is also the only tampermonkey script I run.

I
![Screenshot 2024-06-29 160626](https://github.com/ClangPan/dashboard-unfucker/assets/5592111/3aa4f8d3-5442-420f-a774-a899aaa0998d)
However this error shows up in the console - it seems to involve the unfucker. I hope that's useful.

**Comment by frousties** [comment]
Hmmm at which line does it send you when you click on the link here?:
![image](https://github.com/ClangPan/dashboard-unfucker/assets/99129533/11898a39-b0eb-4181-b7a4-bb43a10276a5)

Also, is the config sidebar there? A few parts of the code with this function are related to it

**Comment by dguenms** [comment]
Yeah, here's the javascript it links to:
![Screenshot 2024-06-29 231531](https://github.com/ClangPan/dashboard-unfucker/assets/5592111/5a03b692-8ea9-4797-8d14-d99edb7deb19)

I'm not sure what you mean by config sidebar. I can't see anything like this in the debug console. Or do you mean on the web page? I think it automatically closes when I reload the page, but the error occurs both when I open it and when I don't.

**Comment by frousties** [comment]
I am talking about this
![image](https://github.com/ClangPan/dashboard-unfucker/assets/99129533/fa5db94b-cb0b-49d0-9a4a-4418d76cc1e2)

Anyway, can you try to see if commenting this line in the script as shown here works?:
![image](https://github.com/ClangPan/dashboard-unfucker/assets/99129533/9b43b63f-e736-4397-b70b-3dfefa1614f4)

If after a page reload this fixes it: do you have a "For you" tab on Tumblr? You probably do, but this part of code is linked to it
When you search "j8ha0" in the Firefox Inspector (F12, first tab), do you find something similar to this?
![image](https://github.com/ClangPan/dashboard-unfucker/assets/99129533/c231ba66-cc0c-420d-9d2d-43aab90840e6)

**Comment by dguenms** [comment]
Commenting that line (directly in the local tampermonkey script - I assume that's what you meant) causes the error no longer to appear in the console but still does not show the icons in the expected way.

I also cannot find "j8ha0" in the inspector:
![Screenshot 2024-06-29 234157](https://github.com/ClangPan/dashboard-unfucker/assets/5592111/a98c9134-2c2d-4094-afe5-cb3d0174778d)

**Comment by frousties** [comment]
Huh, try to see if you can find this line with "data-timeline" instead (it can take a few enter presses)

Also, can you go into the Terminal tab, and input this exact command ``await tumblr.getCssMap()``, then unroll the result, do "Copy Object" and paste the result in a file to send me
![image](https://github.com/ClangPan/dashboard-unfucker/assets/99129533/2b32bdb6-37e8-43aa-a261-3177c47bd42d)

My only guess right now is that somehow the CSS map you're getting is somehow incorrect, which would be *interesting*, to say the least

**Comment by dguenms** [comment]
Yeah, it looks a bit different for me:
![Screenshot 2024-06-29 235919](https://github.com/ClangPan/dashboard-unfucker/assets/5592111/876c0dfe-b51b-4d9d-8a13-c38206ee5e24)

Here's the CSS map I got:
[css.txt](https://github.com/user-attachments/files/16042273/css.txt)

**Comment by frousties** [comment]
Okay so the CSS map is very much functional

Sorry but it's time to get a bit more technical, I'm having trouble understanding what's happening
First of, enable debugging in Tampermonkey
![image](https://github.com/ClangPan/dashboard-unfucker/assets/99129533/c47ea3cb-6a62-4708-adce-0190a9acb769)

Then add ``debugger;`` on top of both calls to ``addUserPortrait()``, and save
![image](https://github.com/ClangPan/dashboard-unfucker/assets/99129533/c09deced-a012-4206-bbaf-2b0cb626b3bb)
![image](https://github.com/ClangPan/dashboard-unfucker/assets/99129533/9cd99626-9c0c-4033-8df2-b8037bfb6d38)

Open the Inspector (F12), then go to the "Debugger" tab, and reload the page
Click the "Resume" button once at the start, then tell me if the page properly stops loading at the place we put the ``debugger;`` line
![image](https://github.com/ClangPan/dashboard-unfucker/assets/99129533/697f1293-ff17-4ace-81df-9d16d93cc5c7)

**Comment by dguenms** [comment]
No problem. It indeed does stop loading after hitting resume and hits the debug statement at line 1744.
![Screenshot 2024-06-30 005110](https://github.com/ClangPan/dashboard-unfucker/assets/5592111/97fe8bfa-abac-4659-bd45-bc96b2e78040)

**Comment by frousties** [comment]
Alright, looking at your first comment again, it seems only half of the header fix is being fired, as the reblog icon IS there

Can you move the ``debugger;`` line over there? See if it stops again, and hovering over the variables to see if there's anything in them
![image](https://github.com/ClangPan/dashboard-unfucker/assets/99129533/38bf36e0-2127-4be7-a181-f771260944ab)
![image](https://github.com/ClangPan/dashboard-unfucker/assets/99129533/7f12fa8b-f171-4726-8cd3-3dd7cd2a2df2)

**Comment by dguenms** [comment]
I did that, and the page load completes without hitting the debugger line.

**Comment by frousties** [comment]
Alright, so that's pretty *interesting*

Let's try a few thing:
- Search ``__stickyContainer`` in the Inspector, see if any results like this one come up (logically none)
![image](https://github.com/ClangPan/dashboard-unfucker/assets/99129533/6bc59f8d-983c-4660-96cb-4fa3f1a55af5)
- Add those two lines, and see if the console prints something out of it in the Console
```js
console.log('postSelector', document.querySelectorAll(postSelector));
console.log('postHeaderTargetSelector', document.querySelectorAll(postHeaderTargetSelector));
```
![image](https://github.com/ClangPan/dashboard-unfucker/assets/99129533/ea83b6ed-b3f4-44cb-b3ca-0fe87b08cb6f)
![image](https://github.com/ClangPan/dashboard-unfucker/assets/99129533/edf2baae-df6e-438d-a37a-d0a4c99763fe)
- Put the ``debugger;`` here instead to see if the mutation really is broken
![image](https://github.com/ClangPan/dashboard-unfucker/assets/99129533/f7c0d515-e858-4a14-b9ee-916b2c2da013)

**Comment by dguenms** [comment]
I did that, and the page load completes without hitting the debugger line.

**Comment by frousties** [comment]
What about the first two points?

**Comment by dguenms** [comment]
Sorry, I missed those - was already pretty sleepy when I tried the last point. Will get back to you later.

**Comment by dguenms** [comment]
Alright:
* `__stickyContainer` has two hits in the `<style id="__s">` and `<script id="__u">` elements - probably expected
* The log statements appear to be hit:

![Screenshot 2024-07-01 222330](https://github.com/ClangPan/dashboard-unfucker/assets/5592111/c36f6723-264f-4d09-8d19-e3572e23b6a8)

**Comment by frousties** [comment]
Ah! Progress! It seems the script can't find the proper HTML element to attach the floating avatars to.

Alright, let's once again go step by step, add these lines here, and show me what it gives you in the console, so I can see which part of the selector fail
```js
      console.log(postHeaderTargetSelector);
      console.log(document.querySelectorAll(postHeaderTargetSelector));
      console.log(document.querySelectorAll(`${keyToCss('main')} > :not(${keyToCss('blogTimeline')}) [data-timeline]:not([data-timeline*='posts/'],${keyToCss('masonry')}) [tabindex='-1'][data-id]`));
      console.log(document.querySelectorAll(`${keyToCss('main')} > :not(${keyToCss('blogTimeline')}) [data-timeline]:not([data-timeline*='posts/'],${keyToCss('masonry')})`));
      console.log(document.querySelectorAll(`${keyToCss('main')} > :not(${keyToCss('blogTimeline')}) [data-timeline]:not(${keyToCss('masonry')})`));
      console.log(document.querySelectorAll(`${keyToCss('main')} > :not(${keyToCss('blogTimeline')})`));
      console.log(document.querySelectorAll(`${keyToCss('main')}`));
```
![image](https://github.com/ClangPan/dashboard-unfucker/assets/99129533/a8a92548-c4c2-4e8b-b79b-f9ecb783655f)

Here's what I get on my end
![image](https://github.com/ClangPan/dashboard-unfucker/assets/99129533/19f393f5-d570-47af-9607-0ccab552df05)

**Comment by dguenms** [comment]
Yeah a bunch of those came back empty:
![Screenshot 2024-07-01 231126](https://github.com/ClangPan/dashboard-unfucker/assets/5592111/1aac3c15-24b4-4973-9071-3afc51c1aceb)

**Comment by frousties** [comment]
Do you hit a line like this if you search ``[data-timeline]`` in the Inspector? :
![image](https://github.com/ClangPan/dashboard-unfucker/assets/99129533/132f074a-dbd8-401e-bcb1-ceedbf7cf5b7)

**Comment by dguenms** [comment]
No:
![Screenshot 2024-07-01 232700](https://github.com/ClangPan/dashboard-unfucker/assets/5592111/788743c4-9af4-4c3b-bd94-9213db87b782)

(I have xkit disabled, by the way.)

**Comment by frousties** [comment]
Alright, now try to replace this line and tell if it fixes it
```js
const postHeaderTargetSelector = `${keyToCss('main')} > :not(${keyToCss('blogTimeline')}) ${keyToCss('timeline')}:not([data-timeline*='posts/'],${keyToCss('masonry')}) [tabindex='-1'][data-id] article:not(.__avatarFixed)`;
```

**Comment by dguenms** [comment]
It did! Thank you so much!

I hope this helps for a general fix. Can you tell me what is different about my setup to cause this?

**Comment by frousties** [comment]
Oh thank GOD

I'll be honest, I have no clue! From the timezone I assume you're American so it can't be region lock thingy, and it's not even a Tumblr version thing as this was how the script was setup for a while now, especially if it worked with the older versions when dragongirlsnout was still maintaining it

It *might* just be Tumblr sneakily redoing some of its internals and rolling it out for a few users, and as usual America would be the first to get the treatment

Anyway, if there isn't any more info you can provide on this subject I'll be closing the issue. Thank you for patiently going along with all that testing ^^

**Comment by dguenms** [comment]
Sure! Glad that I could be of help, and thanks again for patiently debugging this.

The only other thing I can add is that I am pretty sure it worked on the dragongirlsnout version before it broke entirely, and that I am not American. I'm in Germany (and sometimes other European locales for VPN purposes) if that makes any difference.

**Comment by frousties** [comment]
Ah! Sorry for assuming, you were just up very late a few times to help resolve this x)

I really have no idea what happened then, cuz neither did I modify this line, nor did it ever break before, and considering only you for now properly reported on the issue, it's pretty hard to track down
