### ISSUE TITLE
[Compability] Add option to remove border around notification badges

### ISSUE THREAD

**Issue by kateis-cakeis** [ClangPan/dashboard-unfucker#2]
**Describe the bug**
This is more like a minor appearance issue than a straight up bug I suppose, but I thought it was worth a mention anyhow.

When either New XKit's Old Blue is activated or any palette using Palettes for Tumblr is activated, there is a black border around the blue notification square. 
Interestingly, this border can change colour when using the different default palettes that Tumblr itself provides (Low-contrast classic (which does get pretty close to making it invisible), Cement, Canary, Ghost, Snow Bright, and Pride are the only ones that change the border colour)

Turning off New XKit's Old Blue, and disabling the Palettes for Tumblr extension fixes the border. Moreover, turning off the script also fixes this issue. (And as a side note, Pixiel's Old Dashboard doesn't have this issue when Old Blue or Palettes for Tumblr are active, but I know that's likely because this is a script and Old Dashboard isn't)

I have taken steps to try and problem solve my way through this one. I tried turning off various extensions, including uBlock to no avail. I tried messing with the script itself, commenting lines of code, as well as trying to mess with the CSS, but due to not knowing enough about the code itself, I was unable to locate any specific line of code that's causing this issue. Nothing worked unfortunately.

I know you say the script may conflict with New XKit, so apologies for bringing this up if there's no way to fix, but since the issue exists with Palettes for Tumblr as well, it seems as if it's some sort of conflict with any palette changes? Anyhow it is minor so I understand if this isn't a priority. I'm just grateful that this script is active again at all :)

**To Reproduce**
1. Install New XKit or Palettes for Tumblr
2. Either turn on Old Blue for New XKit or select one of the 'Palettes from tumblr's past' for Palettes for Tumblr
3. From here a reload of the page shouldn't be necessary but if you have any notifications (either on home, activity, or inbox) you should be able to see the border

**Screenshots**
_Screenshots with posts or recommended blogs visible have been censored out for the sake of concentrating on the issue_
![Screenshot 2024-07-15 100529](https://github.com/user-attachments/assets/dad31ced-4ba3-4deb-9fba-811cd24a99b1)
^ With Old Blue active
![Screenshot 2024-07-15 102307](https://github.com/user-attachments/assets/cd20443f-9b05-4fa9-aa05-61472a3d855b)
^ With palette 'circa 2016' active
![Screenshot 2024-07-15 101634](https://github.com/user-attachments/assets/8ef18810-fb62-4124-b0b5-0d8934f83a23)
^ With the script turned off
![Screenshot 2024-07-15 102045](https://github.com/user-attachments/assets/c85280dc-da6a-4287-bfe2-7eba421a2731)
^ With Old Blue/Palettes for Tumblr turned off
![Screenshot 2024-07-15 104125](https://github.com/user-attachments/assets/c5fdafa2-3da2-4f2f-aa49-a1cd3f3a533e)
![Screenshot 2024-07-15 104140](https://github.com/user-attachments/assets/b783c290-a19e-4cf7-a9e1-ffab2ea6d89c)
![Screenshot 2024-07-15 104622](https://github.com/user-attachments/assets/586c9383-eae1-4c65-9375-6d57a44b3a6c)
^ How it looks when different default palettes are active

**Version (please complete the following information):**
 - Browser and version: Firefox 128.0
 - Version: 6.1.1
 - OS: Windows 11

**Enabled features**
Exported preferences JSON:
[dashboard unfucker config export 2024-2-15.json](https://github.com/user-attachments/files/16232979/dashboard.unfucker.config.export.2024-2-15.json)

**Additional context**
This could be a me thing, I'm unsure, but it could be a me thing, because for over a year now, or for two years now (unsure for how long), the spellcheck on the post editor has been broken for me. Like it just doesn't work no matter what I do or turn off. So this could just be a me bug. 

That should be it! Of course I'm happy to try and help where I can but my knowledge is very limited.

**Comment by frousties** [comment]
That would be more of an issue on the palette's side, as I do not modify CSS elements to revert to the old UI like Pixiel's UserStyle does

Also, this isn't isolated to XKit's Old Blue or Palettes, it happens with only the script active too
![image](https://github.com/user-attachments/assets/3487d67e-fd3b-4df0-8c5f-56a6b5662328)
It's just harder to see since it's black-on-black

I could definitely add an options for it however, as I expect some people might like having the border and others not

Sorry for the slow response, Github not sending me notifications -.-

**Comment by kateis-cakeis** [comment]
First of all no need to apologise!!! Always annoying when something doesn't send notifications!

And ahhh yeah I see the border there now. Weird and wild, certainly! Definitely unique though with some of the other default palettes!

Yeahhh I like the whole mixing true blue with old blue so having the border there is really stark, if that's something you're up to adding I'm sure people would love it, but that's all up to you and what you feel like doing/adding ^.^ 

Thank you for getting back to me! I appreciate the further insight too :)!

**Comment by frousties** [comment]
![image](https://github.com/user-attachments/assets/84afe7d5-1a55-42b8-9b4b-686d399dce72)

Managed to remove the border, this is how it looks now, what do you think?

**Comment by kateis-cakeis** [comment]
I think it looks great :D Good stuff!

**Comment by frousties** [comment]
Alright then, gonna be implemented in the next release
