### ISSUE TITLE
Feature request: hide the new "Tumblr Premium" ads from the dash.

### ISSUE THREAD

**Issue by anton-exe** [ClangPan/dashboard-unfucker#3]
I am already able to filter the only one that stays on my dash with the uBlock rule `www.tumblr.com##div.FZkjV`, but it would be nice to have a dedicated setting so people don't have to fiddle with custom filters.

**Comment by frousties** [comment]
That should be pretty easy to implement, I'll get to it in a bit!

Sorry for the slow response, Github not sending me notifications -.-

**Comment by frousties** [comment]
Feature implemented, gonna be in next release
![image](https://github.com/user-attachments/assets/d4e70466-2347-4763-af8d-ee04f031a23e)
